---
# This playbooks configured existing openshift cluster to use internal Hawkular
# Pre-reqs:
#  Some kind of block storage class is available
- name: Configure invetory groups
  hosts: all:!control_node:!bastion
  tasks:
    - set_fact:
        openshift_metrics_install_metrics: "{{ override_openshift_metrics_install_metrics }}"
        openshift_hosted_metrics_deploy: "{{ override_openshift_hosted_metrics_deploy }}"

- import_playbook: /usr/share/ansible/openshift-ansible/playbooks/openshift-metrics/config.yml
...
