---
galaxy_info:
  author: gatblau.org
  description: A module to configure firewalld zones and rules. Forked from sean797/ansible-role-firewalld, who in turn forked from marcelnijenhof.firewalld.
  license: BSD
  min_ansible_version: 1.4
  platforms:
  - name: EL
    versions:
    - 7
  - name: Fedora
    versions:
    - 21
    - 22
  categories:
  - networking
dependencies: []
