---
redhat_satellite_fqdn: satellite.myorg.com
redhat_organization_id: myorg
redhat_activationkey: my_ak

repos_to_enable:
  - rhel-7-server-rpms
  - rhel-7-server-extras-rpms
  - rhel-7-server-ose-3.9-rpms
  - rhel-7-fast-datapath-rpms

packages_to_install:
  - wget
  - net-tools
  - bind-utils
  - iptables-services
  - bridge-utils
  - bash-completion
  - kexec-tools
  - sos
  - psacct
  - python-passlib
  - firewalld
  - python-firewall
  - python-ipaddress
  - yum-utils
...
