---
- hosts: override_glusterfs
  roles:
  - { role: register_rhel, tags: ['register_rhel'] }
  - { role: enable_yum_repos, tags: ['enable_yum_repos'] }
  - { role: install_packages, tags: ['install_packages'] }
  - { role: prepare_openshift_node, tags: ['prepare_openshift_node'] }
...
